### ISSUE TITLE
How to run single structures/maps?

### ISSUE THREAD

**Issue by duerrsimon** [dabrze/CheckMyBlob#1]
I'd like to run CheckMyBlob locally but this doesn't seem to be described in the README. 

Basically I want a command line program that has the same options as the webserver: https://checkmyblob.bioreproducibility.org/server/ 
I've tried a few PDB codes (e.g 1pga, 3v1c) on the server and for all of them it gives me an error.

**Comment by dabrze** [comment]
Hi @duerrsimon,

**Comment by dabrze** [comment]
Hi @duerrsimon,

Short answer: this repository does not have the trained models. It's on a closed repo in a different lab, so you would have to do the training on your own. However, the server should work for most structures if they have structure factors (mtz files). Deposit 1pga does not have structure factors (it's a very old deposit), but 3v1c does have them, and I was able to generate predictions: https://checkmyblob.bioreproducibility.org/server/task/77a8af82-7a2b-493c-b7c3-b0ca07eb50ec/. Not sure why it didn't work for you. If you have problems with particular deposits/structures you can write me an e-mail and I'll see if it's fixable.

Long answer: If you want to try and run some of these on your own locally, you would have to first follow the instructions in the GatheData folder to detect and calculate the descriptors for ligands in a structure (unfortunately, that's a bit of a hassle). After that you can play around with the methods available in the Classification folder.

**Comment by dabrze** [comment]
FYI: CMB's prediction for TLA is not that great it detected two separate small molecules (ZN and HOH), but with resolution this high it might as well be something similar to a TLA. However, CMB detected two blobs because the density gap between them was quite high, so something might be off.

**Comment by duerrsimon** [comment]
Thanks for the quick answer. It's unfortunate that the trained models aren't available. Is there an API for the webserver? 

Yesterday for 3v1c I got an error to the likes of "Some REFMAC runs fail".

**Comment by dabrze** [comment]
No, no API or any form of batch input. However, if you are interested in validation I can send you (if I find them) the validation predictions for all the ligands we used for cross validation and testing.
